### ISSUE TITLE
registrationform identifier is already taken

### ISSUE THREAD

**Issue by stefan-kamsker** [unite-cms/unite-cms#153]
there is no feedback to the user if the organzation identifier is already taken on registration form

![bildschirmfoto 2018-06-29 um 12 04 47](https://user-images.githubusercontent.com/34944934/42086939-f5fbfa8c-7b94-11e8-8592-9ac5869475be.png)

**Comment by franzwilding** [comment]
In some controllers we have multiple validation steps, for example the registrationAction. The form itself validates by using the annotations from the registration model. If this form is valid, we create an user and an organization object (https://github.com/unite-cms/unite-cms/blob/master/src/Bundle/RegistrationBundle/Controller/RegistrationController.php#L58). This two objects will be validated again (https://github.com/unite-cms/unite-cms/blob/master/src/Bundle/RegistrationBundle/Controller/RegistrationController.php#L83) and if there are errors, we map them to the form, to display them to the user (https://github.com/unite-cms/unite-cms/blob/master/src/Bundle/RegistrationBundle/Controller/RegistrationController.php#L91).

If you look the the Symfony profiler, you can see that the violations are added to the form, so at least this part is working. So the problem is the correct field mapping.

So solving this bug should not include any new validation steps but only to fix the correct mapping. 

Btw: This bug can be perfectly solved using a TTD approach!
