### ISSUE TITLE
"not_empty" setting in collection

### ISSUE THREAD

**Issue by Benedict-Lojewski** [unite-cms/unite-cms#435]
When you set a field to `"not_empty": true` in a collection, you can't save the content, because it's always saying that this field is needed to be filled in.

for example: 
```javascript
{
  "title": "Foo",
  "identifier": "foo",
  "type": "collection",
  "settings": {
    "min_rows": 1,
    "fields": [
      {
        "title": "Bar",
        "identifier": "bar",
        "type": "text",
        "settings": {
          "not_empty": true
        }
      }
    ]
  }
}
```

When you fill `bar` in and try to save, it doesn't work.
Any Idea how to fix this?

**Comment by stefan-kamsker** [comment]
Hi,

for me it works with the latest release 0.7.4, 

- empty field is not saveable (as expected)
- filled field is saveable

did you try to update?

There is an issue with min_rows setting #438

Best regards!

**Comment by franzwilding** [comment]
Hey @Benedict-Lojewski!

When setting "not_empty" for a field in a collection, this is the expected behaviour: 

- Saving without content in the field should NOT WORK
- Saving with content in the field SHOULD WORK

I can't find any problems here, so if this is not working for you for the latest version of unite cms, please re-open this issue again!
