### ISSUE TITLE
Reference Bug

### ISSUE THREAD

**Issue by MelanieJakob** [unite-cms/unite-cms#511]
If the permissions of a content in list and view is set to member.type == \"admin\" or member.type == \"api\". When you make a reference you get the error „There was a problem rendering this field. Please check the domain configuration or ask an administrator.“

**Comment by franzwilding** [comment]
I will have a look!

**Comment by franzwilding** [comment]
@MelanieJakob thank you for the issue! This happens if the user is not allowed to access the referenced content type (which is required to render the field). I created a PR to make this more clear to the user. 

A even better solution will be possible, once field permissions are implemented (https://github.com/unite-cms/unite-cms/issues/417)
