### ISSUE TITLE
Postgresql/Dbal support

### ISSUE THREAD

**Issue by c33s** [unite-cms/unite-cms#524]
would be nice to be able to use other databases than mysql. 

sidenote: postgresql supports json since version 9.2 (2012-09-10) as mysql started to support it with 5.7 (2015-10-21).

**Comment by franzwilding** [comment]
Yes, that would be great. At the moment we are relaying on https://github.com/ScientaNL/DoctrineJsonFunctions which have some json support for Postgres and mariaDB. 

The first task would be to check, if all of our MySQL json function calls can be done in Postgres as well with this library. 

Do you want to check this out?

**Comment by c33s** [comment]
> Do you want to check this out?

sorry, no. a friend of mine told me to check out unite-cms and no support for postgresql was the first criterion for exclusion.
for me it is always so sad, that often people use frameworks like symfony which have a full DBAL and still the app build out of it is mysql only. 
in your case it is the lack of a full doctrine-json AL (looks like the function set is quite limited for all dbs but mysql)
i assume you use the functions to query the json data directly so https://packagist.org/packages/dunglas/doctrine-json-odm is not really helpful.

**Comment by franzwilding** [comment]
Yes, we are working directly (getting, filtering and setting) with nested json values. Because of this, we are focusing only on mysql for the moment. To relay on mysql and not just doctrine, was an decision, we made. Once, there is a cross-db doctrine extension for json functions available, we are happy to add support for more databases.

I hope, that mysql will work for you at the moment!
